version: "3"

services:

  proxy:
    image: caddy:2.6.2-alpine
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"

  auth:
    image: authelia/authelia:4.37.5
    restart: always
    volumes:
      - ./authelia:/config

  send:
    image: "registry.gitlab.com/timvisee/send:v3.4.22"
    restart: always
    volumes:
      - /var/lib/send/uploads:/uploads
    environment:
      - NODE_ENV=production
      - BASE_URL=https://<DOMAIN>
      - PORT=1443
      - REDIS_HOST=redis
      - FILE_DIR=/uploads
      - DOWNLOAD_COUNTS=1,2,5,10,15,25,50,100,1000
      - DEFAULT_DOWNLOADS=100
      - MAX_DOWNLOADS=1001
      - EXPIRE_TIMES_SECONDS=3600,86400,604800,2592000
      - DEFAULT_EXPIRE_SECONDS=2592000
      - MAX_EXPIRE_SECONDS=2592001

  redis:
    image: 'redis:7.0.8-alpine'
    restart: always
    volumes:
      - send-redis:/data
    command: redis-server --appendonly yes

volumes:
  send-redis:
  caddy_data:
  caddy_config:
